// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMmPrTox3duwO5AJ2-11uTo_Pm8dg9t8o',
    appId: '1:273851780558:web:c68ad2be84f874354daf9f',
    messagingSenderId: '273851780558',
    projectId: 'task-management-darsh',
    authDomain: 'task-management-darsh.firebaseapp.com',
    storageBucket: 'task-management-darsh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpIUyBbuueYDxem_pkU_ZwhFqC0vdxAcU',
    appId: '1:273851780558:android:9a1467b655abe5b64daf9f',
    messagingSenderId: '273851780558',
    projectId: 'task-management-darsh',
    storageBucket: 'task-management-darsh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm9tTomDN7deYYlYlmGMmr4MGNQN3VgDU',
    appId: '1:273851780558:ios:1656ed96abd4f2cc4daf9f',
    messagingSenderId: '273851780558',
    projectId: 'task-management-darsh',
    storageBucket: 'task-management-darsh.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm9tTomDN7deYYlYlmGMmr4MGNQN3VgDU',
    appId: '1:273851780558:ios:1656ed96abd4f2cc4daf9f',
    messagingSenderId: '273851780558',
    projectId: 'task-management-darsh',
    storageBucket: 'task-management-darsh.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMmPrTox3duwO5AJ2-11uTo_Pm8dg9t8o',
    appId: '1:273851780558:web:f21945418d2b124e4daf9f',
    messagingSenderId: '273851780558',
    projectId: 'task-management-darsh',
    authDomain: 'task-management-darsh.firebaseapp.com',
    storageBucket: 'task-management-darsh.firebasestorage.app',
  );
}
